### ISSUE TITLE
Incorrect scrolling behavior on tree viewer page on small displays

### ISSUE THREAD

**Issue by TrueKuehli** [TrueKuehli/PruneTree#34]
**Describe the bug**
On displays with insufficient height, the toolbar on the tree viewer page creates a (permanent) global scrollbar. On mobile displays this can lead to accidental scrolling when trying to move around the tree.

**To Reproduce**
1. Create a really short browser window or use the dev tools device emulation with a short height.
2. View any tree
3. A global scrollbar is present, letting the user accidentally scroll below the actual tree viewer.

**Expected behavior**
There should never be a global scrollbar on the tree viewer page. Instead, the dropdown menus should only ever get as tall as the screen, and have their own scrollbar if necessary.

**Screenshots**
![Screenshot of the issue](https://github.com/TrueKuehli/PruneTree/assets/13822861/ddbdd000-40e6-4cd2-9618-81c62dbd3537)

**Comment by vimal20002** [comment]
Please assign this to me i have worked on same issues earlier.

**Comment by TrueKuehli** [comment]
@vimal20002 Thanks for offering to help! I'll assign you right away. Let me know if you have any questions :+1:

**Comment by TrueKuehli** [comment]
Hi @vimal20002, just checking in, are you still working on a fix? If not I could take a look at it towards the end of this week.

**Comment by TrueKuehli** [comment]
Closed by 891509c7c4cbf09ea8f1bc49ccdfd81ced51d0cd
