### ISSUE TITLE
Stop YouTube from loading until user consent is given

### ISSUE THREAD

**Issue by TrueKuehli** [TrueKuehli/PruneTree#47]
To improve user privacy we shouldn't load the YouTube player on the main page until a user explicitly clicks a button confirming they want the YouTube video to be shown. This button should be placed in the same position as the video, and a placeholder should be placed around it that takes up the same amount of space as the video player will. This ensures that no unncessary content shifts happen when the user presses the button.

Optionally we can remember the user's choice (using e.g. an entry in localStorage) so that users don't have to click on the button every time they want the video to be shown.

**Comment by jCabala** [comment]
Hi, could I work on this issue?

**Comment by TrueKuehli** [comment]
@jCabala That would be great thank you! I'll assign the issue to you right away, if you have any questions, please feel free to reach out to me!

**Comment by jCabala** [comment]
Hi, I'm about to make a pull request and have 2 questions:
1. How do I check if the pipeline passed?
2. How do I bind this issue with the pull request?

**Comment by TrueKuehli** [comment]
GitHub automatically recognizes some keywords like "Closes" in the PR description, so if you include `Closes #47` in the PR description this issue should be closed automatically once the PR is merged.

Both the build and linting pipelines run automatically when you submit the PR and should show the results on the PR page once they're done running. You can also update the PR after the fact, so don't worry if any of the pipeline steps fail initially. It might also make sense to check if those steps pass locally first (`npm run build`, `npm run lint:scripts`, and `npm run lint:styles`), since it can take a while for GitHub to run all those steps 😅
